### ISSUE TITLE
No information about mapping mojepanstwo.pl ids to TERYT

### ISSUE THREAD

**Issue by tzoltak** [pbiecek/SmarterPoland#10]
In API for BDL internal mojepanstwo.pl teritorial units ids are used. However there is no function in the package that would allow to get information about what teritorial unit a given value of the id refers to. In particular no mapping of these ids to TERYT is provided.

**Comment by pbiecek** [comment]
Fixed with 5affbe6c93880fbed6b4a29a077fea777b39316a
Now you can use getMPgminy() to get more informations about each subcounty (like TERYT codes and id).
Also, I've updated the doc for getBDLseries
