### ISSUE TITLE
getBDLtree() don't work

### ISSUE THREAD

**Issue by tzoltak** [pbiecek/SmarterPoland#7]
getBDLtree() is throwing an error which indicates that it is trying to open an url that doesn't exist.

**Comment by pbiecek** [comment]
Fix with d0e2cf8676e616937a62518adb77785ccb9bfb21

Unfortunately the https://api-v3.mojepanstwo.pl/bdl/categories returns an empty list
So I am using https://api-v3.mojepanstwo.pl/dane/bdl_wskazniki in order to get list of indicators
